/* Generated automatically by H5make_libsettings -- do not edit */



/* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
 * Copyright by The HDF Group.                                               *
 * Copyright by the Board of Trustees of the University of Illinois.         *
 * All rights reserved.                                                      *
 *                                                                           *
 * This file is part of HDF5.  The full HDF5 copyright notice, including     *
 * terms governing use, modification, and redistribution, is contained in    *
 * the COPYING file, which can be found at the root of the source code       *
 * distribution tree, or in https://support.hdfgroup.org/ftp/HDF5/releases.  *
 * If you do not have access to either file, you may request a copy from     *
 * help@hdfgroup.org.                                                        *
 * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
 *
 * Created:		Jan 15, 2018
 *			yamamoto yuki <yymmt@yymmt.kuchem.kyoto-u.ac.jp>
 *
 * Purpose:		This machine-generated source code contains
 *			information about the library build configuration
 *
 * Modifications:
 *
 *	DO NOT MAKE MODIFICATIONS TO THIS FILE!
 *	It was generated by code in `H5make_libsettings.c'.
 *
 *-------------------------------------------------------------------------
 */

char H5libhdf5_settings[]=
	"	    SUMMARY OF THE HDF5 CONFIGURATION\n"
	"	    =================================\n"
	"\n"
	"General Information:\n"
	"-------------------\n"
	"                   HDF5 Version: 1.10.1\n"
	"                  Configured on: Mon Jan 15 04:04:46 JST 2018\n"
	"                  Configured by: yymmt@yymmt.kuchem.kyoto-u.ac.jp\n"
	"                    Host system: x86_64-unknown-linux-gnu\n"
	"              Uname information: Linux yymmt.kuchem.kyoto-u.ac.jp 2.6.32-696.16.1.el6.x86_64 #1 SMP Wed Nov 15 16:51:15 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux\n"
	"                       Byte sex: little-endian\n"
	"             Installation point: /home/yamamoto/local/devel/moltypes\n"
	"\n"
	"Compiling Options:\n"
	"------------------\n"
	"                     Build Mode: production\n"
	"              Debugging Symbols: no\n"
	"                        Asserts: no\n"
	"                      Profiling: no\n"
	"             Optimization Level: high\n"
	"\n"
	"Linking Options:\n"
	"----------------\n"
	"                      Libraries: static, shared\n"
	"  Statically Linked Executables: \n"
	"                        LDFLAGS: -L/home/yamamoto/local/devel/moltypes/lib\n"
	"                     H5_LDFLAGS: \n"
	"                     AM_LDFLAGS:  -L/home/yamamoto/local/devel/moltypes/lib\n"
	"                Extra libraries: -lz -ldl -lm \n"
	"                       Archiver: ar\n"
	"                         Ranlib: ranlib\n"
	"\n"
	"Languages:\n"
	"----------\n"
	"                              C: yes\n"
	"                     C Compiler: /opt/intel/compilers_and_libraries_2017.2.174/linux/mpi/intel64/bin/mpiicc ( Intel(R) C Intel(R) 64 Compiler Version 17.0.2.174 Build 20170213)\n"
	"                       CPPFLAGS: -I/home/yamamoto/local/devel/moltypes/include\n"
	"                    H5_CPPFLAGS: -D_GNU_SOURCE -D_POSIX_C_SOURCE=200112L   -DNDEBUG -UH5_DEBUG_API\n"
	"                    AM_CPPFLAGS:  -I/home/yamamoto/local/devel/moltypes/include\n"
	"                        C Flags: -O3 -xHost -ip -no-prec-div -static-intel -fPIC\n"
	"                     H5 C Flags:   -std=c99 -Wcheck -Wall  -Wl,-s  -O3\n"
	"                     AM C Flags: \n"
	"               Shared C Library: yes\n"
	"               Static C Library: yes\n"
	"\n"
	"\n"
	"                        Fortran: no\n"
	"\n"
	"                            C++: no\n"
	"\n"
	"                           Java: no\n"
	"\n"
	"\n"
	"Features:\n"
	"---------\n"
	"                  Parallel HDF5: yes\n"
	"             High-level library: yes\n"
	"                   Threadsafety: no\n"
	"            Default API mapping: v110\n"
	" With deprecated public symbols: yes\n"
	"         I/O filters (external): deflate(zlib)\n"
	"                            MPE: \n"
	"                     Direct VFD: no\n"
	"                        dmalloc: no\n"
	" Packages w/ extra debug output: none\n"
	"                    API tracing: no\n"
	"           Using memory checker: no\n"
	"Memory allocation sanity checks: no\n"
	"            Metadata trace file: no\n"
	"         Function stack tracing: no\n"
	"      Strict file format checks: no\n"
	"   Optimization instrumentation: no\n"
;

